formatter: "markdown document"
output-values: {enabled: false, from: ""}
sort: { enabled: true, by: name }
sections: { hide: [providers, resources, data-sources] }
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  html: false
  indent: 2
  lockfile: true
  read-comments: true
  required: false
  sensitive: false
  type: false
